### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by marcojacobsNL** [PositiveTechnologies/ghidra_nodejs#2]
When I try to dragndrop the file into ghidra I must specify a language, but what language do I need to provide?
You maybe got a way to get in contact with you?

**Comment by lab313ru** [comment]
Please, check the supported versions list. If Ghidra doesn't select our Loader,  then your jsc file has unsupported version.

**Comment by marcojacobsNL** [comment]
I tried to use a sample from your samples folder, but it wouldn’t auto select a language

i’m also not exactly sure if I made the zip correctly, what type of import type must I select when importing the repo?

**Comment by lab313ru** [comment]
Download the latest release from the Releases page, and jnstall it according to the instruction.
