### ISSUE TITLE
Other node versions support

### ISSUE THREAD

**Issue by louistb** [PositiveTechnologies/ghidra_nodejs#3]
First of all, amazing work on this add-on. 

This is more a question then a issue, i wanted to know if you guys are planning on adding other versions of node JS and i was curious on how similar is the V8 bytecode from on version of node to the other.

I tried other versions of node that are not supported and as expected it did not work.

Thanks

**Comment by lab313ru** [comment]
Hi, thanks for your feedback!

Currently, we don't have a plan to add other versions support, but we will add them if they will happen in our work projects.:)

Fortunately, minor version number changes usually don't require many efforts to add that version support. Major version changes may require a lot of work, especially, if the devs have added some new runtime functions and opcodes.

I think we will publish some manual about adding a new version support.

**Comment by louistb** [comment]
Thanks for the response, would be amazing to have a manual on how to port your plugin to other versions.

**Comment by KamikazePlatypus** [comment]
@lab313ru Do keep us updated on that manual!
