### ISSUE TITLE
Error fetching constant poolrecord

### ISSUE THREAD

**Issue by cameralis** [PositiveTechnologies/ghidra_nodejs#4]
Hi! I get this error when decompiling. I installed the extension from the Releases tab. Maybe my v8 version is incompatible?

```
Low-level Error: Error fetching constant poolrecord: 
Cannot invoke "ghidra.program.model.util.ObjectPropertyMap.getObject(ghidra.program.model.address.Address)" 
because "map" is null
```

**Comment by lab313ru** [comment]
Hi. Does this error happen after reopening your project, or just during the initial loading of that binary?

**Comment by cameralis** [comment]
I see this error in the side-bar, in the "Decompiler" tab
