### ISSUE TITLE
Why is bytecode different in x86 and x64 architectures

### ISSUE THREAD

**Issue by Zhxhh** [PositiveTechnologies/ghidra_nodejs#7]
Bytecode should be platform-independent. Do you know why bytecode generation is different in different architectures? （This problem has nothing to do with this repo, it's just a technical consultation）:)

**Comment by ntlyapova** [comment]
Hello! 
You are right, it is independent, the bitness refers to the structure of the generated jsc files by different versions of Node.js. If you look at https://github.com/PositiveTechnologies/ghidra_nodejs/tree/main/data/languages, you will see only one file describing the instructions.
if you are interested in the details of the difference, I think Vladimir can tell you more.

**Comment by Zhxhh** [comment]
> Hello!
> You are right, it is independent, the bitness refers to the structure of the generated jsc files by different versions of Node.js. If you look at https://github.com/PositiveTechnologies/ghidra_nodejs/tree/main/data/languages, you will see only one file describing the instructions.
> if you are interested in the details of the difference, I think Vladimir can tell you more.

Thanks for your reply！But why  are sample/raw_x64.jsc and sample/rax_x86.jsc different?
![image](https://user-images.githubusercontent.com/32181911/126059055-f8f50633-8e36-43f8-9f83-2de5aaeade88.png)

**Comment by lab313ru** [comment]
The Parser uses a different SMI value size for x86 and x64. Such values are present in ConstantPool objects and in some alignment things. Implementation of the bytecode is really the same, but how exactly it will be serialized/deserialized depends on the architecture bitness.

In result, a different SMI value will lead to a different reference (destination) to use in a disassembler (and so by the decompiler).

To find more details about the difference, use `getPointerSize` keyword to search withing this repo.

Thank you for your question!
